# This is a basic workflow to help you get started with Actions

name: CI

env:
  MIRROR_URL: "https://github.com/EpitechPromo2027/B-DOP-200-PAR-2-2-popeye-barbara-bruna1.nogueira-de-menezes"
  EXECUTABLES: "result/node_modules"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches-ignore:    
      - 'ga-ignore-'
  pull_request:
    branches-ignore:    
      - 'ga-ignore-'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_coding_style"
  check_coding_style:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            $MIRROR_URL
          ssh_private_key:
            ${{ secrets.EPITECH_SSH }}
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm install

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          check.sh $(pwd) $(pwd),
          echo "::error"
